# Generated by Django 3.1.3 on 2021-01-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_pmc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='rank',
            field=models.CharField(choices=[('2Lt', '2Lt'), ('Lt', 'Lt'), ('Capt', 'Capt'), ('Maj', 'Maj'), ('Lt Col', 'Lt Col'), ('Guest', 'Guest')], max_length=150),
        ),
    ]
