# Generated by Django 3.1.3 on 2021-01-03 20:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealorder',
            name='time_placed',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 20, 26, 41, 217982, tzinfo=utc)),
        ),
    ]
