# Generated by Django 3.1.3 on 2020-11-25 23:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealorder',
            name='time_placed',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 23, 1, 20, 125788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mealorder',
            name='total_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mealorderitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(),
        ),
    ]
