# Generated by Django 3.1.3 on 2021-01-10 21:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210103_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealorder',
            name='time_placed',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 21, 48, 32, 303499, tzinfo=utc)),
        ),
    ]
