# Generated by Django 3.1.3 on 2020-12-10 22:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201125_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealorderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mealorder'),
        ),
        migrations.AlterField(
            model_name='mealorder',
            name='time_placed',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 22, 30, 15, 220051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mealorderitem',
            name='item',
            field=models.CharField(max_length=30),
        ),
    ]
